# Generated by Django 2.2.28 on 2023-11-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='puissance',
            field=models.TextField(default=10),
            preserve_default=False,
        ),
    ]
